### ISSUE TITLE
Defect: Calculating Savings is showing UNDEFINED in the Results field

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-volvotrucks-ca-broken#3]
**URL:** 
https://www.volvotrucks.ca/en-ca/trucks/powertrain/d13tc/turbo-compounding-calculator/

**Steps to reproduce**
- Navigate to the Turbo Compounding Calculator section
- Go to Baseline Powertrain and Emissions and go to the first field
- Click the dropdown
- View the options in the dropdown
- Go to Next-Gen D13TC Powertrain
- View the options in the dropdown
- Scroll down to Results

**Expected results**
The Baseline Powertrain and Emissions dropdown shows options, Next-Gen D13TC Powertrain shows options and the Results displays the resulting calculations in the graphs for MPG Improvement, Savings Each Year, Fuel Usage, and Cumulative Savings.

**Actual results**
The Baseline Powertrain and Emissions dropdown doesn't show options, Next-Gen D13TC Powertrain doesn't show options and the Results doesn't display the resulting calculations in the graphs for MPG Improvement, Savings Each Year, Fuel Usage, and Cumulative Savings.

<img width="854" alt="CA Calculator 1" src="https://user-images.githubusercontent.com/126615590/233482956-13c0516e-9c03-45ed-ac54-9519b524048e.PNG">
<img width="897" alt="CA Calculator 2" src="https://user-images.githubusercontent.com/126615590/233482965-31d442ea-4b16-4792-b7d8-4627806e19fa.PNG">
<img width="889" alt="CA Calculator 3" src="https://user-images.githubusercontent.com/126615590/233483539-1d341d90-dfc1-4f25-88b8-f78b27dfcd9a.PNG">
<img width="897" alt="CA Calculator 4" src="https://user-images.githubusercontent.com/126615590/233483545-5a2ccd7c-7e44-4226-a9c2-e930602f6a9d.PNG">
<img width="881" alt="CA Calculator 5" src="https://user-images.githubusercontent.com/126615590/233483546-ddda94c8-97e2-4b7b-85e2-728726ff85dd.PNG">

**Comment by synox** [comment]
Note: this issue is for the "original" site, as this is not yet migrated to Franklin.
